language: node_js

node_js:
    - "node"
    - "10"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - npm run build

script:
    - npm start & npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
